// This file is automatically generated. Do not edit it directly.
// Auth middleware - simplified for client-only app
import { createClient } from '@supabase/supabase-js'
import type { Database } from './types'

// Since we're now client-only, auth is handled on the client-side
// This is kept for compatibility but is a no-op
export const requireSupabaseAuth = async (payload: any) => {
  // Client-side auth is handled by Supabase session management
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['VITE_SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['VITE_SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  // Return the payload as-is; real auth check happens on client
  return payload;
};
