// This file is automatically generated. Do not edit it directly.
// Auth utilities for client-only app (no longer using TanStack Start middleware)
import { supabase } from './client'

// Get auth headers for API calls
export async function getAuthHeaders() {
  const { data } = await supabase.auth.getSession()
  const token = data.session?.access_token
  return token ? { Authorization: `Bearer ${token}` } : {}
}

// Middleware-like function for attaching auth (kept for compatibility)
export const attachSupabaseAuth = async ({ next }: { next: (opts: any) => Promise<any> }) => {
  const headers = await getAuthHeaders()
  return next({ headers })
}
